DATASET:
    NAME: 'ILSVRC'
    IMG_SHAPE: [224, 224]
    IMG_CHANNELS: 3

MODEL:
    NETWORK: 'RESNET'
    LAYER: ['BN', 'CONV', 'RELU']
    DEPTH: 50

NORMALIZER:
    MAX_VALUE: 255.0
    MEAN: [0.485, 0.456, 0.406]
    STD: [0.229, 0.224, 0.225]
